# Generated by Django 3.1.4 on 2020-12-06 11:32

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='photo_main',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='photo_main'),
        ),
    ]
